#!/usr/bin/env python3
"""Import a Unitree G1 URDF and verify it carries PhysX collision schemas.

This is intentionally a physics-asset validation, not a claim that a Gaussian
splat itself produces collision.  Pair it with a collision proxy generated by
``build_splat_collision_proxy.sh`` for a hybrid scene.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--robot-urdf", type=Path, required=True)
    parser.add_argument("--robot-package-root", type=Path, required=True)
    parser.add_argument("--package-name", default="g1_description")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    urdf = args.robot_urdf.resolve()
    package_root = args.robot_package_root.resolve()
    if not urdf.is_file():
        raise FileNotFoundError(urdf)
    if not package_root.is_dir():
        raise FileNotFoundError(package_root)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    args.report.parent.mkdir(parents=True, exist_ok=True)

    from isaacsim import SimulationApp

    simulation_app = SimulationApp({"headless": True})
    try:
        import omni.kit.app
        from isaacsim.asset.importer.urdf import (
            URDFImporter,
            URDFImporterConfig,
        )
        from pxr import Usd, UsdPhysics

        manager = omni.kit.app.get_app().get_extension_manager()
        manager.set_extension_enabled_immediate("isaacsim.asset.importer.urdf", True)
        config = URDFImporterConfig(
            urdf_path=str(urdf),
            usd_path=str(args.output_dir.resolve()),
            collision_from_visuals=False,
            collision_type="Convex Decomposition",
            allow_self_collision=True,
            fix_base=False,
        )
        config.ros_package_paths = [
            {args.package_name: str(package_root)},
        ]
        usd_path = URDFImporter(config).import_urdf()
        if not usd_path:
            raise RuntimeError("Isaac Sim URDFImporter did not return a USD path.")
        stage = Usd.Stage.Open(str(usd_path))
        if stage is None:
            raise RuntimeError(f"Unable to open imported robot USD: {usd_path}")
        collision_paths = [
            str(prim.GetPath())
            for prim in stage.Traverse()
            if prim.HasAPI(UsdPhysics.CollisionAPI)
        ]
        articulation_paths = [
            str(prim.GetPath())
            for prim in stage.Traverse()
            if prim.HasAPI(UsdPhysics.ArticulationRootAPI)
        ]
        if not collision_paths:
            raise AssertionError("Imported G1 has no PhysX collision schemas.")
        if not articulation_paths:
            raise AssertionError("Imported G1 has no PhysX articulation root.")
        report = {
            "schema_version": "isaacsim-g1-urdf-import-smoke/v1",
            "urdf": str(urdf),
            "package_root": str(package_root),
            "imported_usd": str(usd_path),
            "collision_prim_count": len(collision_paths),
            "collision_prim_examples": collision_paths[:12],
            "articulation_root_count": len(articulation_paths),
            "articulation_root_examples": articulation_paths[:12],
            "result": "PASS",
            "scope": (
                "Validates robot collision/articulation authoring only. A Gaussian "
                "scene requires a separate PhysX collision proxy."
            ),
        }
        args.report.write_text(
            json.dumps(report, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        print("ISAACSIM_G1_URDF_IMPORT_OK " + json.dumps(report, sort_keys=True))
    finally:
        simulation_app.close()


if __name__ == "__main__":
    main()
